/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as OrderCodeRouteImport } from './routes/order.$code'
import { Route as AuthenticatedOwnerRouteImport } from './routes/_authenticated/owner'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCashierRouteImport } from './routes/_authenticated/cashier'
import { Route as AuthenticatedOwnerIndexRouteImport } from './routes/_authenticated/owner.index'
import { Route as AuthenticatedCashierIndexRouteImport } from './routes/_authenticated/cashier.index'
import { Route as AppSettingsPrinterRouteImport } from './routes/app/settings.printer'
import { Route as AuthenticatedOwnerStaffRouteImport } from './routes/_authenticated/owner.staff'
import { Route as AuthenticatedOwnerProductsRouteImport } from './routes/_authenticated/owner.products'
import { Route as AuthenticatedOwnerCategoriesRouteImport } from './routes/_authenticated/owner.categories'
import { Route as AuthenticatedCashierPosRouteImport } from './routes/_authenticated/cashier.pos'
import { Route as AuthenticatedCashierInventoryRouteImport } from './routes/_authenticated/cashier.inventory'
import { Route as AuthenticatedCashierHistoryRouteImport } from './routes/_authenticated/cashier.history'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const OrderCodeRoute = OrderCodeRouteImport.update({
  id: '/order/$code',
  path: '/order/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOwnerRoute = AuthenticatedOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCashierRoute = AuthenticatedCashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerIndexRoute = AuthenticatedOwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedOwnerRoute,
} as any)
const AuthenticatedCashierIndexRoute =
  AuthenticatedCashierIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCashierRoute,
  } as any)
const AppSettingsPrinterRoute = AppSettingsPrinterRouteImport.update({
  id: '/settings/printer',
  path: '/settings/printer',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthenticatedOwnerStaffRoute = AuthenticatedOwnerStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedOwnerRoute,
} as any)
const AuthenticatedOwnerProductsRoute =
  AuthenticatedOwnerProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerCategoriesRoute =
  AuthenticatedOwnerCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedCashierPosRoute = AuthenticatedCashierPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedCashierRoute,
} as any)
const AuthenticatedCashierInventoryRoute =
  AuthenticatedCashierInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedCashierRoute,
  } as any)
const AuthenticatedCashierHistoryRoute =
  AuthenticatedCashierHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedCashierRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cashier': typeof AuthenticatedCashierRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/owner': typeof AuthenticatedOwnerRouteWithChildren
  '/order/$code': typeof OrderCodeRoute
  '/app/': typeof AppIndexRoute
  '/cashier/history': typeof AuthenticatedCashierHistoryRoute
  '/cashier/inventory': typeof AuthenticatedCashierInventoryRoute
  '/cashier/pos': typeof AuthenticatedCashierPosRoute
  '/owner/categories': typeof AuthenticatedOwnerCategoriesRoute
  '/owner/products': typeof AuthenticatedOwnerProductsRoute
  '/owner/staff': typeof AuthenticatedOwnerStaffRoute
  '/app/settings/printer': typeof AppSettingsPrinterRoute
  '/cashier/': typeof AuthenticatedCashierIndexRoute
  '/owner/': typeof AuthenticatedOwnerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/order/$code': typeof OrderCodeRoute
  '/app': typeof AppIndexRoute
  '/cashier/history': typeof AuthenticatedCashierHistoryRoute
  '/cashier/inventory': typeof AuthenticatedCashierInventoryRoute
  '/cashier/pos': typeof AuthenticatedCashierPosRoute
  '/owner/categories': typeof AuthenticatedOwnerCategoriesRoute
  '/owner/products': typeof AuthenticatedOwnerProductsRoute
  '/owner/staff': typeof AuthenticatedOwnerStaffRoute
  '/app/settings/printer': typeof AppSettingsPrinterRoute
  '/cashier': typeof AuthenticatedCashierIndexRoute
  '/owner': typeof AuthenticatedOwnerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/cashier': typeof AuthenticatedCashierRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/owner': typeof AuthenticatedOwnerRouteWithChildren
  '/order/$code': typeof OrderCodeRoute
  '/app/': typeof AppIndexRoute
  '/_authenticated/cashier/history': typeof AuthenticatedCashierHistoryRoute
  '/_authenticated/cashier/inventory': typeof AuthenticatedCashierInventoryRoute
  '/_authenticated/cashier/pos': typeof AuthenticatedCashierPosRoute
  '/_authenticated/owner/categories': typeof AuthenticatedOwnerCategoriesRoute
  '/_authenticated/owner/products': typeof AuthenticatedOwnerProductsRoute
  '/_authenticated/owner/staff': typeof AuthenticatedOwnerStaffRoute
  '/app/settings/printer': typeof AppSettingsPrinterRoute
  '/_authenticated/cashier/': typeof AuthenticatedCashierIndexRoute
  '/_authenticated/owner/': typeof AuthenticatedOwnerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/cashier'
    | '/dashboard'
    | '/owner'
    | '/order/$code'
    | '/app/'
    | '/cashier/history'
    | '/cashier/inventory'
    | '/cashier/pos'
    | '/owner/categories'
    | '/owner/products'
    | '/owner/staff'
    | '/app/settings/printer'
    | '/cashier/'
    | '/owner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/order/$code'
    | '/app'
    | '/cashier/history'
    | '/cashier/inventory'
    | '/cashier/pos'
    | '/owner/categories'
    | '/owner/products'
    | '/owner/staff'
    | '/app/settings/printer'
    | '/cashier'
    | '/owner'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/app'
    | '/auth'
    | '/_authenticated/cashier'
    | '/_authenticated/dashboard'
    | '/_authenticated/owner'
    | '/order/$code'
    | '/app/'
    | '/_authenticated/cashier/history'
    | '/_authenticated/cashier/inventory'
    | '/_authenticated/cashier/pos'
    | '/_authenticated/owner/categories'
    | '/_authenticated/owner/products'
    | '/_authenticated/owner/staff'
    | '/app/settings/printer'
    | '/_authenticated/cashier/'
    | '/_authenticated/owner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OrderCodeRoute: typeof OrderCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/order/$code': {
      id: '/order/$code'
      path: '/order/$code'
      fullPath: '/order/$code'
      preLoaderRoute: typeof OrderCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cashier': {
      id: '/_authenticated/cashier'
      path: '/cashier'
      fullPath: '/cashier'
      preLoaderRoute: typeof AuthenticatedCashierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/': {
      id: '/_authenticated/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof AuthenticatedOwnerIndexRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/cashier/': {
      id: '/_authenticated/cashier/'
      path: '/'
      fullPath: '/cashier/'
      preLoaderRoute: typeof AuthenticatedCashierIndexRouteImport
      parentRoute: typeof AuthenticatedCashierRoute
    }
    '/app/settings/printer': {
      id: '/app/settings/printer'
      path: '/settings/printer'
      fullPath: '/app/settings/printer'
      preLoaderRoute: typeof AppSettingsPrinterRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_authenticated/owner/staff': {
      id: '/_authenticated/owner/staff'
      path: '/staff'
      fullPath: '/owner/staff'
      preLoaderRoute: typeof AuthenticatedOwnerStaffRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/products': {
      id: '/_authenticated/owner/products'
      path: '/products'
      fullPath: '/owner/products'
      preLoaderRoute: typeof AuthenticatedOwnerProductsRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/categories': {
      id: '/_authenticated/owner/categories'
      path: '/categories'
      fullPath: '/owner/categories'
      preLoaderRoute: typeof AuthenticatedOwnerCategoriesRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/cashier/pos': {
      id: '/_authenticated/cashier/pos'
      path: '/pos'
      fullPath: '/cashier/pos'
      preLoaderRoute: typeof AuthenticatedCashierPosRouteImport
      parentRoute: typeof AuthenticatedCashierRoute
    }
    '/_authenticated/cashier/inventory': {
      id: '/_authenticated/cashier/inventory'
      path: '/inventory'
      fullPath: '/cashier/inventory'
      preLoaderRoute: typeof AuthenticatedCashierInventoryRouteImport
      parentRoute: typeof AuthenticatedCashierRoute
    }
    '/_authenticated/cashier/history': {
      id: '/_authenticated/cashier/history'
      path: '/history'
      fullPath: '/cashier/history'
      preLoaderRoute: typeof AuthenticatedCashierHistoryRouteImport
      parentRoute: typeof AuthenticatedCashierRoute
    }
  }
}

interface AuthenticatedCashierRouteChildren {
  AuthenticatedCashierHistoryRoute: typeof AuthenticatedCashierHistoryRoute
  AuthenticatedCashierInventoryRoute: typeof AuthenticatedCashierInventoryRoute
  AuthenticatedCashierPosRoute: typeof AuthenticatedCashierPosRoute
  AuthenticatedCashierIndexRoute: typeof AuthenticatedCashierIndexRoute
}

const AuthenticatedCashierRouteChildren: AuthenticatedCashierRouteChildren = {
  AuthenticatedCashierHistoryRoute: AuthenticatedCashierHistoryRoute,
  AuthenticatedCashierInventoryRoute: AuthenticatedCashierInventoryRoute,
  AuthenticatedCashierPosRoute: AuthenticatedCashierPosRoute,
  AuthenticatedCashierIndexRoute: AuthenticatedCashierIndexRoute,
}

const AuthenticatedCashierRouteWithChildren =
  AuthenticatedCashierRoute._addFileChildren(AuthenticatedCashierRouteChildren)

interface AuthenticatedOwnerRouteChildren {
  AuthenticatedOwnerCategoriesRoute: typeof AuthenticatedOwnerCategoriesRoute
  AuthenticatedOwnerProductsRoute: typeof AuthenticatedOwnerProductsRoute
  AuthenticatedOwnerStaffRoute: typeof AuthenticatedOwnerStaffRoute
  AuthenticatedOwnerIndexRoute: typeof AuthenticatedOwnerIndexRoute
}

const AuthenticatedOwnerRouteChildren: AuthenticatedOwnerRouteChildren = {
  AuthenticatedOwnerCategoriesRoute: AuthenticatedOwnerCategoriesRoute,
  AuthenticatedOwnerProductsRoute: AuthenticatedOwnerProductsRoute,
  AuthenticatedOwnerStaffRoute: AuthenticatedOwnerStaffRoute,
  AuthenticatedOwnerIndexRoute: AuthenticatedOwnerIndexRoute,
}

const AuthenticatedOwnerRouteWithChildren =
  AuthenticatedOwnerRoute._addFileChildren(AuthenticatedOwnerRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCashierRoute: typeof AuthenticatedCashierRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOwnerRoute: typeof AuthenticatedOwnerRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCashierRoute: AuthenticatedCashierRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOwnerRoute: AuthenticatedOwnerRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsPrinterRoute: typeof AppSettingsPrinterRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppSettingsPrinterRoute: AppSettingsPrinterRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OrderCodeRoute: OrderCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
